from __future__ import annotations

from datetime import timedelta
from typing import Protocol

from .models import Message


class Gateway(Protocol):
    """مرز ارتباطی با سروش؛ هر عملیاتی باید از API واقعی گروه عبور کند."""

    async def is_group_admin(self, chat_id: str, user_id: str) -> bool: ...
    async def get_message(self, chat_id: str, message_id: int) -> Message | None: ...
    async def delete_message(self, chat_id: str, message_id: int) -> None: ...
    async def restrict_member(self, chat_id: str, user_id: str, duration: timedelta) -> None: ...
    async def ban_member(self, chat_id: str, user_id: str) -> None: ...
    async def send_message(self, chat_id: str, text: str) -> None: ...
    async def list_members(self, chat_id: str, limit: int = 500) -> list[dict[str, str]]: ...
    async def inspect_message(self, message: Message) -> Message: ...
    async def set_default_permissions(self, chat_id: str, permissions: dict[str, bool]) -> bool: ...
